name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - run: npm ci

      - run: npm run test:unit
        env:
          JWT_SECRET_ACCESS_TOKEN: 9ab0f1edab31a2a241cf1e3225d14931
          JWT_SECRET_REFRESH_TOKEN: 62a4861e75e1c95b39c0469e3d18e666
          JWT_EXPIRES_IN_REFRESH_TOKEN: 7d
          JWT_EXPIRES_IN_ACCESS_TOKEN: 10m
          SENDGRID_API_KEY: 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
          APP_URL_DEVLOPMENT: http://localhost:3333/api
          APP_URL_PRODUCTION: https://api-olharlaser.onrender.com/api
          NODE_ENV: development
          DATABASE_URL: postgresql://kaiodev:1ebd9d49b83bd87fb8f9e069dd8bd47e@localhost:5432/dbOlharLaser?schema=public
          ASAAS_API_KEY: $aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNjU4NDQ6OiRhYWNoXzIxODQ3YTUxLTdhYzctNGZjZi1iZjBmLTlkNWYyYjQzM2Q0NA==
          ASAAS_API_URL: https://sandbox.asaas.com/api/v3
          CHARACTERS: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
          FIREBASE_BUCKET: gs://olharlaser.appspot.com
          FIREBASE_CLIENT_EMAIL: firebase-adminsdk-zxkjk@olharlaser.iam.gserviceaccount.com
          FIREBASE_PROJECT_ID: olharlaser
          FIREBASE_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggS
          FOLDER_TMP: ./src/tmp